# Default cms bundle config.
cms:
    site_name: 'RevisionTen CMS'

    # Cache configuration.
    disable_cache_workaround: false

    # Email configuration for user management.
    mailer_return_path: 'postmaster@some-website.com'
    mailer_from: 'info@some-website.com'
    mailer_sender: 'info@some-website.com'

    # Two Factor Authentication configuration.
    use_mail_codes: false # Set this to true If you want to receive login codes by mail, set this to false to use Google Authenticator.
    mail_code_lifetime: 5 # Minutes until mailed code expires.

    # Solr configuration.
    solr_host: 'localhost'
    solr_port: 8983
    solr_collection: null # The name of your collection

    # CKEditor configuration.
    ckeditor_config:
        uiColor: '#ffffff'
        allowedContent: true
        extraAllowedContent: 'span(*);i(*)'
        stylesSet: 'bootstrap4styles:/bundles/cms/js/ckeditor-styles.js' # To use ckeditor defaults use: default:/bundles/cms/libs/dist/ckeditor/styles.js
        contentsCss:
            - 'https://use.fontawesome.com/releases/v5.5.0/css/all.css'
            - '/bundles/cms/example-template-files/bootstrap.min.css'
            - '/bundles/cms/libs/dist/ckeditor/contents.css'
            - '/bundles/cms/css/ckeditor.css'
        toolbar:
            - { name: 'basicstyles', items: [ 'Source', 'PasteFromWord', 'RemoveFormat', '-', 'Undo', 'Redo', 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript' ] }
            - { name: 'tools', items: [ 'Maximize' ] }
            - { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'Link', 'Unlink', 'Anchor', 'Table', 'HorizontalRule', 'Iframe' ] }
            - { name: 'basicstyles2', items: [ 'Styles', 'Format' ] }

    # Admin menu configuration.
    admin_menu:
        Content:
            - { entity: PageStreamRead, icon: 'file-alt' }
            - { entity: PageStreamReadArchive, icon: 'archive' }
            - { entity: Alias, icon: 'link' }
            - { entity: FileRead, icon: 'download' }
        Structure:
            - { entity: Website, icon: 'globe-africa' }
            - { entity: MenuRead, icon: 'bars' }
            - { entity: FormRead, icon: 'mail-bulk' }
            - { entity: FormSubmission, icon: 'envelope' }
        Settings:
            - { entity: UserRead, icon: 'users' }
            - { entity: RoleRead, icon: 'user-shield' }
            - { entity: Task, icon: 'tasks' }
            - { entity: EventStreamObject, icon: 'clock' }

    # Menu configuration.
    menus:
        Main Menu:
            template: '@cms/Menu/main.html.twig'
        Footer Menu:
            template: '@cms/Menu/footer.html.twig'
    menu_items:
        Page:
            class: RevisionTen\CMS\Form\Menu\Page
            template: '@cms/Menu/Items/page.html.twig'
        Link:
            class: RevisionTen\CMS\Form\Menu\Link
            template: '@cms/Menu/Items/link.html.twig'
        Divider:
            class: RevisionTen\CMS\Form\Menu\Divider
            template: '@cms/Menu/Items/divider.html.twig'

    # Controller choices for controller page element.
    controller:
        Login Form:
            action: 'RevisionTen\CMS\Controller\SecurityController::loginForm'
        Fulltext Search Results:
            action: 'RevisionTen\CMS\Controller\FrontendController::fulltextSearch'

    # Page configuration.
    page_type: RevisionTen\CMS\Form\PageType
    page_metatype: RevisionTen\CMS\Form\PageMetaType
    page_languages:
        English: 'en'
        German: 'de'
        French: 'fr'
    page_templates:
        Simple Page:
            template: '@cms/layout.html.twig'
            # Options to further customize the page type:
            #metatype: RevisionTen\CMS\Form\Meta\LocalBusinessMetaType
            #solr_serializer: App\Serializer\PageSerializer # Must implement RevisionTen\CMS\Interface\SolrSerializerInterface
            #alias_prefix:
            #    en: '/simple-page/' # Defaults to '/'
            #    de: '/einfache-seite/'
            #permissions:
            #    list: 'list_simple_page'
            #    search: 'search_simple_page'
            #    new: 'create_simple_page'
            #    edit: 'edit_simple_page'
            #    delete: 'delete_simple_page'
            #websites: [1, 2] # Array of website ids this template is available on
    page_elements:
        Section:
            class: RevisionTen\CMS\Form\Elements\Section
            type: 'Section' # Optional property, defines how the element behaves in the frontend editor.
            template: '@cms/Layout/section.html.twig'
            icon: 'fa fa-th-large'
            children:
                - 'Row'
        Row:
            class: RevisionTen\CMS\Form\Elements\Row
            type: 'Row' # Optional property, defines how the element behaves in the frontend editor.
            template: '@cms/Layout/row.html.twig'
            icon: 'fa fa-window-maximize'
            children:
                - 'Column'
            styles:
                center columns horizontal: 'justify-content-center'
                align columns right: 'justify-content-end'
                center columns vertical: 'align-items-center'
                no gutters: 'no-gutters'
        Column:
            class: RevisionTen\CMS\Form\Elements\Column
            type: 'Column' # Optional property, defines how the element behaves in the frontend editor.
            template: '@cms/Layout/column.html.twig'
            icon: 'fa fa-columns'
            children:
                - 'all'
            styles:
                stretch items: 'd-flex flex-wrap align-items-stretch'
                align items center: 'd-flex flex-wrap align-items-center'
                align items end: 'd-flex flex-wrap align-items-end'
        Text:
            class: RevisionTen\CMS\Form\Elements\Text
            template: '@cms/Layout/text.html.twig'
            public: true
            icon: 'fa fa-file'
        Form:
            class: RevisionTen\CMS\Form\Elements\Form
            template: '@cms/Layout/form.html.twig'
            public: true
            icon: 'fab fa-wpforms'
        Image:
            class: RevisionTen\CMS\Form\Elements\Image
            template: '@cms/Layout/image.html.twig'
            public: true
            icon: 'fa fa-image'
        Images:
            class: RevisionTen\CMS\Form\Elements\Images
            template: '@cms/Layout/images.html.twig'
            public: true
            icon: 'fa fa-images'
        File:
            class: RevisionTen\CMS\Form\Elements\File
            template: '@cms/Layout/file.html.twig'
            public: true
            icon: 'fa fa-file'
        Controller:
            class: RevisionTen\CMS\Form\Elements\Controller
            template: '@cms/Layout/controller.html.twig'
            public: true
            icon: 'fa fa-magic'
        Timing:
            class: RevisionTen\CMS\Form\Elements\Timing
            template: '@cms/Layout/timing.html.twig'
            public: true
            icon: 'fa fa-clock'
            children:
                - 'all'
        Anchor:
            class: RevisionTen\CMS\Form\Elements\Anchor
            template: '@cms/Layout/anchor.html.twig'
            public: true
            icon: 'fas fa-anchor'
        Card:
            class: RevisionTen\CMS\Form\Elements\Card
            template: '@cms/Layout/card.html.twig'
            public: true
            icon: 'fas fa-id-card'
        Youtube:
            class: RevisionTen\CMS\Form\Elements\Youtube
            template: '@cms/Layout/youtube.html.twig'
            public: true
            icon: 'fab fa-youtube'
        Vimeo:
            class: RevisionTen\CMS\Form\Elements\Vimeo
            template: '@cms/Layout/vimeo.html.twig'
            public: true
            icon: 'fab fa-vimeo'
