forms:
    load_easyadmin_config: false
    item_types:
        #GroupItem:
        #    class: RevisionTen\Forms\Form\Items\GroupItem
        #    icon: 'fa-object-group'
        TextItem:
            class: RevisionTen\Forms\Form\Items\TextItem
            icon: 'fa-comment'
        TextAreaItem:
            class: RevisionTen\Forms\Form\Items\TextAreaItem
            icon: 'fa-book'
        EmailItem:
            class: RevisionTen\Forms\Form\Items\EmailItem
            icon: 'fa-at'
        CheckboxItem:
            class: RevisionTen\Forms\Form\Items\CheckboxItem
            icon: 'fa-check-square'
        ChoiceItem:
            class: RevisionTen\Forms\Form\Items\ChoiceItem
            icon: 'fa-list-ul'
        EntityItem:
            class: RevisionTen\Forms\Form\Items\EntityItem
            icon: 'fa-database'
        MarkupItem:
            class: RevisionTen\Forms\Form\Items\MarkupItem
            icon: 'fa-code'
        SubmitItem:
            class: RevisionTen\Forms\Form\Items\SubmitItem
            icon: 'fa-paper-plane'

twig:
    paths:
        '%kernel.project_dir%/vendor/revision-ten/cms/Templates': cms
        '%kernel.project_dir%/vendor/easycorp/easyadmin-bundle/src/Resources/views': EasyAdminBase
        '%kernel.project_dir%/vendor/revision-ten/cms/Templates/EasyAdmin': EasyAdmin
    form_themes:
          - '@cms/Form/form_theme.html.twig'

services:
    RevisionTen\CMS\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']
    RevisionTen\CMS\Security\CodeAuthenticator:
        autowire: true
        public: false
    RevisionTen\CMS\Security\BasicAuthenticator:
        autowire: true
        public: false
    RevisionTen\CMS\Command\Console\UserCreateCommand:
        autoconfigure: true
        autowire: true
        public: false
        tags: [console.command]
    RevisionTen\CMS\Command\Console\UserSecretCommand:
        autoconfigure: true
        autowire: true
        public: false
        tags: [console.command]
    RevisionTen\CMS\Services\SecretService:
        autowire: true
        public: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Services\PageService:
        autowire: true
        public: true
    RevisionTen\CMS\Form\Types\UploadType:
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $project_dir: '%kernel.project_dir%'
        tags: [form.type]
    RevisionTen\CMS\Form\Types\DoctrineType:
        autoconfigure: true
        autowire: true
        public: true
        tags: [form.type]
    RevisionTen\CMS\Form\Elements\Form:
        autoconfigure: true
        autowire: true
        public: true
        tags: [form.type]
    RevisionTen\CMS\Form\Menu\Page:
        autoconfigure: true
        autowire: true
        public: true
        tags: [form.type]
    RevisionTen\CMS\Form\Elements\Controller:
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $config: '%cms%'
        tags: [form.type]
    RevisionTen\CMS\Listener\:
        resource: '../../Listener/*'
        exclude: '../../Listener/{PageBaseListener.php}'
        public: true
        autowire: true

framework:
    translator:
        paths:
            - '%kernel.project_dir%/vendor/revision-ten/cms/Resources/translations'
    session:
        # The native PHP session handler will be used
        handler_id: ~
        #cookie_secure: false # This determines whether cookies should only be sent over secure connections.
        #cookie_httponly: true # This determines whether cookies should only be accessible through the HTTP protocol. This means that the cookie won't be accessible by scripting languages, such as JavaScript. This setting can effectively help to reduce identity theft through XSS attacks.
    # Add template.engines for the ckeditor.
    templating:
        engines: ['twig']

doctrine:
    orm:
        mappings:
            CmsBundle:
                mapping: true
                type: annotation
                dir: 'Model'
                alias: CmsBundle
                prefix: 'RevisionTen\CMS\Model'
                is_bundle: true

gregwar_image:
    web_dir: "%kernel.project_dir%/public"

easy_admin:
    site_name: '<span class="sidebar-toggle sidebar-toggle-editor" data-toggle="offcanvas" role="button"><img class="svg-inline--fa appicon" src="/bundles/cms/icons/drop.svg"></span> CMS'
    design:
        color_scheme: 'light'
        brand_color: '#2f323e'
        assets:
            css:
                - 'bundles/cms/css/easyadmin.css'
            js:
                - 'bundles/cms/libs/dist/ckeditor/ckeditor.js'
                - 'bundles/cms/js/admin-backend.js'
        form_theme: '@cms/Form/form_theme_easyadmin.html.twig'
        menu:
            - { label: 'Dashboard', route: 'cms_dashboard', icon: 'nope fas fa-tachometer-alt' }
            - { label: 'Contents' }
            - { entity: PageStreamRead, icon: 'file' }
            - { entity: PageStreamReadArchive, icon: 'nope fas fa-archive' }
            - { entity: Alias, icon: 'nope fas fa-link' }
            - { label: 'Structure' }
            - { entity: Website, icon: 'nope fas fa-compass' }
            - { label: 'Menues', route: 'cms_list_menues', icon: 'bars' }
            - { label: 'Forms', entity: 'FormRead', icon: 'nope fab fa-wpforms' }
            - { label: 'Settings' }
            - { entity: EventStreamObject, icon: 'clock' }
    formats:
        date:     'd.m.Y'
        time:     'H:i'
        datetime: 'd.m.Y H:i'
    entities:
        Alias:
            label: 'Paths'
            class: RevisionTen\CMS\Model\Alias
            list:
                fields:
                    #- 'uuid'
                    - 'id'
                    - { property: 'path', template: '@cms/Admin/alias_path_column.html.twig' }
                    - { property: 'pageStreamRead', type: 'object', template: '@cms/Admin/alias_pagestreamred_column.html.twig' }
                    - { property: 'redirect', label: '404 Redirect', template: '@cms/Admin/alias_redirect_column.html.twig' }
                    - { property: 'priority', label: 'Search Engine Priority', template: '@cms/Admin/alias_priority_column.html.twig' }
            form:
                fields:
                    - 'path'
                    - 'pageStreamRead'
                    - 'redirect'
                    - { property: 'priority', label: 'Search Engine Priority', type: 'choice', type_options: { choices: { 'Very low': 0.1, 'Low': 0.3, 'Normal': 0.5, 'High': 0.6, 'Very high': 1 } } }
        Website:
            label: 'Websites'
            class: RevisionTen\CMS\Model\Website
            list:
                fields:
                    #- 'uuid'
                    - 'title'
                    - 'domains'
            form:
                fields:
                    - 'title'
                    - { property: 'domains', type: 'Symfony\Component\Form\Extension\Core\Type\CollectionType', type_options: { entry_type: 'RevisionTen\CMS\Form\Admin\DomainType', entry_options: { label: false }, by_reference: false, allow_delete: true, delete_empty: true, allow_add: true } }
        PageStreamRead:
            label: 'Pages'
            class: RevisionTen\CMS\Model\PageStreamRead
            templates:
                list: '@cms/Admin/list-pages.html.twig'
            list:
                sort: ['modified', 'DESC']
                dql_filter: 'entity.deleted IS NULL OR entity.deleted = 0'
                actions:
                    - { name: 'cms_edit_aggregate', type: 'route', label: 'Edit aggregate', icon: 'edit' }
                    - { name: 'cms_clone_aggregate', type: 'route', label: 'Clone page', icon: 'clone' }
                    - { name: 'cms_delete_aggregate', type: 'route', label: 'Delete page', icon: 'trash', css_class: 'text-danger' }
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    #- 'uuid'
                    - 'title'
                    - 'version'
                    - 'language'
                    - { property: 'website', template: '@cms/Admin/website_column.html.twig' }
                    - { property: 'published', type: 'boolean' }
                    - { property: 'template', template: '@cms/Admin/template_column.html.twig' }
                    - { property: 'created', type: 'datetime' }
                    - { property: 'modified', type: 'datetime' }
        PageStreamReadArchive:
            label: 'Archive'
            class: RevisionTen\CMS\Model\PageStreamRead
            list:
                sort: ['modified', 'DESC']
                dql_filter: 'entity.deleted = 1'
                actions:
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    #- 'uuid'
                    - 'title'
                    - 'version'
                    - 'language'
                    - { property: 'published', type: 'boolean' }
                    - { property: 'template', template: '@cms/Admin/template_column.html.twig' }
                    - { property: 'created', type: 'datetime' }
                    - { property: 'modified', type: 'datetime' }
        EventStreamObject:
            label: 'Log'
            class: RevisionTen\CQRS\Model\EventStreamObject
            show:
                actions:
                    - '-edit'
                    - '-delete'
                fields:
                    - { property: 'payload', template: '@cms/Admin/payload_column.html.twig' }
            list:
                help: 'This list shows all persisted events.'
                sort: ['id', 'DESC']
                actions:
                    - { name: 'show', label: 'inspect payload', icon: 'eye' }
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    - { property: 'uuid', label: 'Title', template: '@cms/Admin/uuid_column.html.twig' }
                    - { property: 'message', label: 'Message', template: '@cms/Admin/message_column.html.twig' }
                    - 'version'
                    - { property: 'created', type: 'datetime' }
                    - { property: 'user', template: '@cms/Admin/user_column.html.twig' }
        FormRead:
            label: 'Forms'
            class: RevisionTen\Forms\Model\FormRead
            templates:
                list: '@cms/Admin/list-forms.html.twig'
            list:
                sort: ['modified', 'DESC']
                dql_filter: 'entity.deleted IS NULL OR entity.deleted = 0'
                actions:
                    - { name: 'forms_edit_aggregate', type: 'route', label: 'edit form', icon: 'edit' }
                    - { name: 'forms_clone_aggregate', type: 'route', label: 'clone form', icon: 'clone' }
                    - { name: 'forms_delete_aggregate', type: 'route', label: 'delete form', icon: 'trash', css_class: 'text-danger' }
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    - 'title'
                    - 'version'
                    - { property: 'created', type: 'datetime' }
                    - { property: 'modified', type: 'datetime' }