
twig:
    globals:
        pageTemplateConfig: '%cms.page_templates%' # Needed to check permissions in admin templates.
        backend_service: '@RevisionTen\CMS\Services\BackendService'

framework:
    translator:
        paths:
            - '%kernel.project_dir%/vendor/revision-ten/cms/Resources/translations'

# Use param for gregwar config so it becomes overwriteable.
parameters:
    gregwar_image_web_dir: "%kernel.project_dir%/public"
gregwar_image:
    web_dir: "%gregwar_image_web_dir%"

cocur_slugify:
    lowercase: true
    separator: '-'
    rulesets: ['german', 'default'] # List of rulesets: https://github.com/cocur/slugify/tree/master/Resources/rules

doctrine:
    orm:
        dql:
            string_functions:
                JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch

