forms:
    load_easyadmin_config: false
    item_types:
        #GroupItem:
        #    class: RevisionTen\Forms\Form\Items\GroupItem
        #    icon: 'fa-object-group'
        TextItem:
            class: RevisionTen\Forms\Form\Items\TextItem
            icon: 'fa-comment'
        TextAreaItem:
            class: RevisionTen\Forms\Form\Items\TextAreaItem
            icon: 'fa-book'
        EmailItem:
            class: RevisionTen\Forms\Form\Items\EmailItem
            icon: 'fa-at'
        CheckboxItem:
            class: RevisionTen\Forms\Form\Items\CheckboxItem
            icon: 'fa-check-square'
        ChoiceItem:
            class: RevisionTen\Forms\Form\Items\ChoiceItem
            icon: 'fa-list-ul'
        EntityItem:
            class: RevisionTen\Forms\Form\Items\EntityItem
            icon: 'fa-database'
        MarkupItem:
            class: RevisionTen\Forms\Form\Items\MarkupItem
            icon: 'fa-code'
        HiddenItem:
            class: RevisionTen\Forms\Form\Items\HiddenItem
            icon: 'fa-eye-slash'
        SubmitItem:
            class: RevisionTen\Forms\Form\Items\SubmitItem
            icon: 'fa-paper-plane'

twig:
    paths:
        '%kernel.project_dir%/vendor/revision-ten/cms/Templates': cms
        '%kernel.project_dir%/vendor/easycorp/easyadmin-bundle/src/Resources/views': EasyAdminBase
        '%kernel.project_dir%/vendor/revision-ten/cms/Templates/FormsBundle': forms
        '%kernel.project_dir%/vendor/revision-ten/cms/Templates/EasyAdmin': EasyAdmin
    form_themes:
          - '@cms/Form/form_theme.html.twig'

framework:
    translator:
        paths:
            - '%kernel.project_dir%/vendor/revision-ten/cms/Resources/translations'
    session:
        # The native PHP session handler will be used
        handler_id: ~
        #cookie_secure: false # This determines whether cookies should only be sent over secure connections.
        #cookie_httponly: true # This determines whether cookies should only be accessible through the HTTP protocol. This means that the cookie won't be accessible by scripting languages, such as JavaScript. This setting can effectively help to reduce identity theft through XSS attacks.
    # Add template.engines for the ckeditor.
    templating:
        engines: ['twig']

doctrine:
    orm:
        mappings:
            CmsBundle:
                mapping: true
                type: annotation
                dir: 'Model'
                alias: CmsBundle
                prefix: 'RevisionTen\CMS\Model'
                is_bundle: true

gregwar_image:
    web_dir: "%kernel.project_dir%/public"

easy_admin:
    site_name: '<img class="revision-ten-logo" src="/bundles/cms/icons/logo.svg"> %cms.site_name%'
    design:
        assets:
            css:
                - 'https://fonts.googleapis.com/css?family=Rubik'
                - 'https://use.fontawesome.com/releases/v5.5.0/css/all.css'
                - 'https://use.fontawesome.com/releases/v5.5.0/css/v4-shims.css'
                - 'bundles/cms/css/trix.css?v=%cms.version%'
                - 'bundles/cms/css/jquery-ui.min.css?v=%cms.version%'
                - 'bundles/cms/css/easyadmin.css?v=%cms.version%'
            js:
                - 'bundles/cms/js/bootstrap/popper.min.js?v=%cms.version%'
                - 'bundles/cms/js/bootstrap/bootstrap.min.js?v=%cms.version%'
                - 'bundles/cms/libs/dist/trix.js?v=%cms.version%'
                - 'bundles/cms/libs/dist/ckeditor/ckeditor.js?v=%cms.version%'
                - 'bundles/cms/libs/dist/jquery-sortable-min.js?v=%cms.version%'
                - 'bundles/cms/js/admin-backend.js?v=%cms.version%'
        menu:
            - { label: 'Dashboard', route: 'cms_dashboard', icon: 'nope fas fa-tachometer-alt' }
            - { label: 'Content' }
            - { entity: PageStreamRead, icon: 'nope fas fa-file-alt' }
            - { entity: PageStreamReadArchive, icon: 'nope fas fa-archive' }
            - { entity: Alias, icon: 'nope fas fa-link' }
            - { label: 'Files', route: 'cms_file_list', icon: 'nope fas fa-download' }
            - { label: 'Structure' }
            - { entity: Website, icon: 'nope fas fa-globe-africa' }
            - { entity: MenuRead, label: 'Menus', icon: 'bars' }
            - { label: 'Forms', entity: 'FormRead', icon: 'nope fas fa-mail-bulk' }
            - { label: 'Settings' }
            - { entity: UserRead, icon: 'users' }
            - { entity: EventStreamObject, icon: 'clock' }
    formats:
        date:     'd.m.Y'
        time:     'H:i'
        datetime: 'd.m.Y H:i'
    entities:
        Alias:
            label: 'Paths'
            class: RevisionTen\CMS\Model\Alias
            list:
                dql_filter: 'entity.controller IS NULL'
                actions:
                    - { name: 'edit', label: '', title: 'Edit', icon: 'edit' }
                    - { name: 'delete', label: '', title: 'Delete', icon: 'trash', css_class: 'text-danger' }
                fields:
                    #- 'uuid'
                    - 'id'
                    - { property: 'path', template: '@cms/Admin/Alias/List/path.html.twig' }
                    - { property: 'language', template: '@cms/Admin/Alias/List/language.html.twig' }
                    - { property: 'website', template: '@cms/Admin/Alias/List/website.html.twig' }
                    - { property: 'pageStreamRead', type: 'object', template: '@cms/Admin/Alias/List/page.html.twig' }
                    #- { property: 'controller', template: '@cms/Admin/Alias/List/controller.html.twig' }
                    - { property: 'redirect', label: '404 Redirect', template: '@cms/Admin/Alias/List/redirect.html.twig' }
                    - { property: 'priority', label: 'Search Engine Priority', template: '@cms/Admin/Alias/List/priority.html.twig' }
            form:
                fields:
                    - 'path'
                    - { property: 'language', type: 'choice', type_options: { choices: '%cms.page_languages%' } }
                    - 'website'
                    - 'pageStreamRead'
                    - 'redirect'
                    - { property: 'priority', label: 'Search Engine Priority', type: 'choice', type_options: { choices: { 'Very low': 0.1, 'Low': 0.3, 'Normal': 0.5, 'High': 0.6, 'Very high': 1 } } }
        Website:
            label: 'Websites'
            class: RevisionTen\CMS\Model\Website
            list:
                actions:
                    - { name: 'edit', label: '', title: 'Edit', icon: 'edit' }
                    - { name: 'delete', label: '', title: 'Delete', icon: 'trash', css_class: 'text-danger' }
                    - '-delete'
                fields:
                    #- 'uuid'
                    - 'title'
                    - 'defaultLanguage'
                    - 'domains'
                    - 'aliases'
            form:
                fields:
                    - 'id'
                    - { property: 'title', type: 'text' }
                    - { property: 'siteVerification', type: 'text', label: 'Google Site Verification Meta-Tag' }
                    - { property: 'defaultLanguage', type: 'choice', type_options: { choices: '%cms.page_languages%' } }
                    #- { property: 'domains', type: 'Symfony\Component\Form\Extension\Core\Type\CollectionType', type_options: { entry_type: 'RevisionTen\CMS\Form\Admin\DomainType', entry_options: { label: false }, by_reference: false, allow_delete: true, delete_empty: true, allow_add: true } }
        PageStreamRead:
            label: 'Pages'
            class: RevisionTen\CMS\Model\PageStreamRead
            templates:
                list: '@cms/Admin/Page/list.html.twig'
            list:
                sort: ['modified', 'DESC']
                dql_filter: 'entity.deleted IS NULL OR entity.deleted = 0'
                actions:
                    - { name: 'cms_edit_aggregate', type: 'route', label: '', title: 'Edit aggregate', icon: 'edit' }
                    - { name: 'cms_clone_aggregate', type: 'route', label: '', title: 'Clone page', icon: 'clone' }
                    - { name: 'cms_delete_aggregate', type: 'route', label: '', title: 'Delete page', icon: 'trash', css_class: 'text-danger' }
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    #- 'uuid'
                    - { property: 'title', css_class: 'title-truncate' }
                    - 'version'
                    - 'language'
                    - { property: 'website', template: '@cms/Admin/Website/List/website.html.twig' }
                    - { property: 'published', type: 'boolean' }
                    - { property: 'template', label: "Page template", template: '@cms/Admin/Page/List/template.html.twig' }
                    - { property: 'created', type: 'datetime' }
                    - { property: 'modified', type: 'datetime' }
        PageStreamReadArchive:
            label: 'Archive'
            class: RevisionTen\CMS\Model\PageStreamRead
            list:
                sort: ['modified', 'DESC']
                dql_filter: 'entity.deleted = 1'
                actions:
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    #- 'uuid'
                    - { property: 'title', css_class: 'title-truncate' }
                    - 'version'
                    - 'language'
                    - { property: 'website', template: '@cms/Admin/Website/List/website.html.twig' }
                    - { property: 'published', type: 'boolean' }
                    - { property: 'template', label: "Page template", template: '@cms/Admin/Page/List/template.html.twig' }
                    - { property: 'created', type: 'datetime' }
                    - { property: 'modified', type: 'datetime' }
        EventStreamObject:
            label: 'Log'
            class: RevisionTen\CQRS\Model\EventStreamObject
            show:
                actions:
                    - '-edit'
                    - '-delete'
                fields:
                    - { property: 'payload', template: '@cms/Admin/Event/Show/payload.html.twig' }
            list:
                help: 'This list shows all persisted events.'
                sort: ['id', 'DESC']
                actions:
                    #- { name: 'show', label: 'inspect payload', icon: 'eye' }
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    - { property: 'uuid', label: 'Title', template: '@cms/Admin/User/List/uuid.html.twig' }
                    - { property: 'message', label: 'Message', template: '@cms/Admin/Event/List/message.html.twig' }
                    - 'version'
                    - { property: 'created', type: 'datetime' }
                    - { property: 'user', template: '@cms/Admin/User/List/small.html.twig' }
        UserRead:
            label: 'Users'
            class: RevisionTen\CMS\Model\UserRead
            show:
                actions:
                    - '-edit'
                    - '-delete'
                fields:
                    - { property: 'id', label: 'Avatar', template: '@cms/Admin/User/List/medium.html.twig' }
                    - { property: 'username' }
                    - { property: 'email' }
                    - { property: 'devices' }
                    - { property: 'ips' }
            list:
                sort: ['id', 'DESC']
                actions:
                    - { name: 'show', title: 'View', label: '', icon: 'eye' }
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    - { property: 'id', label: 'Avatar', template: '@cms/Admin/User/List/medium.html.twig' }
                    - { property: 'username', label: 'Username' }
                    - { property: 'email', label: 'Email' }
        FormRead:
            label: 'Forms'
            class: RevisionTen\Forms\Model\FormRead
            templates:
                list: '@cms/Admin/Forms/list.html.twig'
            list:
                sort: ['modified', 'DESC']
                dql_filter: 'entity.deleted IS NULL OR entity.deleted = 0'
                actions:
                    - { name: 'forms_edit_aggregate', type: 'route', title: 'edit form', label: '', icon: 'edit' }
                    - { name: 'forms_clone_aggregate', type: 'route', title: 'clone form', label: '', icon: 'clone' }
                    - { name: 'forms_delete_aggregate', type: 'route', title: 'delete form', label: '', icon: 'trash', css_class: 'text-danger' }
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    - 'title'
                    - 'version'
                    - { property: 'created', type: 'datetime' }
                    - { property: 'modified', type: 'datetime' }
        MenuRead:
            label: 'Menus'
            class: RevisionTen\CMS\Model\MenuRead
            templates:
                list: '@cms/Admin/Menu/list.html.twig'
            list:
                sort: ['title', 'DESC']
                actions:
                    - '-new'
                    - '-edit'
                    - '-delete'
                    - { name: 'cms_edit_menu', type: 'route', label: '', title: 'Edit aggregate', icon: 'edit' }
                fields:
                    #- 'uuid'
                    - { property: 'title', label: 'Menu', css_class: 'title-truncate', template: '@cms/Admin/Menu/List/title.html.twig' }
                    - 'version'
                    - 'language'
                    - { property: 'website', template: '@cms/Admin/Website/List/website.html.twig' }
