cms:
    permissions:
        General:
            do_everything:
                label: 'Do everything'
            list_generic:
                label: 'List generic entity'
            search_generic:
                label: 'Search generic entity'
            edit_generic:
                label: 'Edit generic entity'
            show_generic:
                label: 'Show generic entity'
            create_generic:
                label: 'Create generic entity'
            delete_generic:
                label: 'Delete generic entity'
        Page:
            page_list:
                label: 'List pages'
            page_search:
                label: 'Search pages'
            page_create:
                label: 'Create page'
            page_edit:
                label: 'Edit page'
            page_delete:
                label: 'Delete page'
            page_clone:
                label: 'Clone page'
            page_publish:
                label: 'Publish page'
            page_unpublish:
                label: 'Unpublish page'
            page_schedule:
                label: 'Schedule page'
            page_submit_changes:
                label: 'Submit page changes'
            page_inspect:
                label: 'Inspect page'
            page_change_seo_settings:
                label: 'Change SEO settings'
        Alias:
            alias_list:
                label: 'List aliases'
            alias_search:
                label: 'Search aliases'
            alias_create:
                label: 'Create alias'
            alias_edit:
                label: 'Edit alias'
            alias_delete:
                label: 'Delete alias'
        Menu:
            menu_list:
                label: 'List menus'
            menu_search:
                label: 'Search menus'
            menu_create:
                label: 'Create menu'
            menu_edit:
                label: 'Edit menu'
        Form:
            form_list:
                label: 'List forms'
            form_search:
                label: 'Search forms'
            form_create:
                label: 'Create form'
            form_edit:
                label: 'Edit form'
            form_delete:
                label: 'Delete form'
            form_clone:
                label: 'Clone form'
            form_submissions:
                label: 'List form submissions'
            form_submissions_delete:
                label: 'Delete form submissions'
        File:
            file_list:
                label: 'List files'
            file_search:
                label: 'Search files'
            file_create:
                label: 'Create file'
            file_edit:
                label: 'Edit file'
        Website:
            website_list:
                label: 'List websites'
            website_search:
                label: 'Search websites'
            website_create:
                label: 'Create website'
            website_edit:
                label: 'Edit website'
        Role:
            role_list:
                label: 'List roles'
            role_search:
                label: 'Search roles'
            role_create:
                label: 'Create role'
            role_edit:
                label: 'Edit role'
            role_show:
                label: 'Show role'
        User:
            user_list:
                label: 'List users'
            user_search:
                label: 'Search users'
            user_edit:
                label: 'Edit user'
            user_show:
                label: 'Show user'
        Event:
            event_list:
                label: 'List events'
            event_search:
                label: 'Search events'
            event_show:
                label: 'Show events'
        Task:
            task_list:
                label: 'List tasks'
            task_search:
                label: 'Search tasks'
            task_show:
                label: 'Show tasks'
