security:
    session_fixation_strategy: none
    erase_credentials: false
    encoders:
        RevisionTen\CMS\Entity\UserRead:
            algorithm: bcrypt
    providers:
        db_provider:
            entity:
                class: RevisionTen\CMS\Entity\UserRead
                property: username
    firewalls:
        # Protect the Admin Area with the Code Authenticator.
        admin:
            methods: [GET, POST, PUT, PATCH, DELETE]
            pattern:    ^/admin
            stateless: false
            provider: db_provider
            guard:
                authenticators:
                    - RevisionTen\CMS\Security\CodeAuthenticator
            logout:
                invalidate_session: true
                path: cms_logout
                target: /
                #handlers: [RevisionTen\CMS\EventListener\LogoutListener]
        # Protect the Code Authenticator with the Basic Authenticator.
        code:
            methods: [GET, POST, PUT, PATCH, DELETE]
            pattern:    ^/code
            stateless: false
            provider: db_provider
            guard:
                authenticators:
                    - RevisionTen\CMS\Security\BasicAuthenticator
            logout:
                invalidate_session: true
                path: cms_logout
                target: /
