services:
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    # Controllers.
    RevisionTen\CMS\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../../Controller'
        exclude: '../../Controller/{FrontendController.php,PageController.php,AdminController.php,EntityController.php}'
        tags: ['controller.service_arguments']
    RevisionTen\CMS\Controller\PageController:
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            $fullContainer: '@service_container'
    RevisionTen\CMS\Controller\FrontendController:
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Controller\AdminController:
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Controller\EntityController:
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Services\BackendService:
        autoconfigure: true
        autowire: true
        arguments:
            $config: '%cms%'

    # Various.
    RevisionTen\CMS\DataCollector\CmsCollector:
        autowire: true
        tags:
            - name:     data_collector
              template: '@CMS/Backend/Profiler/layout.html.twig'
              id:       'cms.cms_collector'
        public: false
    RevisionTen\CMS\Repository\AliasRepository:
        autowire: true
        autoconfigure: true
        arguments:
            $entityClass: 'RevisionTen\CMS\Entity\Alias'
    RevisionTen\CMS\Twig\CmsExtension:
        autowire: true
        public: true
        tags: [twig.extension]
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Twig\MenuExtension:
        autowire: true
        public: true
        tags: [twig.extension]
    RevisionTen\CMS\Twig\MenuRuntime:
        autowire: true
        public: true
        tags: [twig.runtime]
        arguments:
            $config: '%cms%'

    # Security.
    RevisionTen\CMS\Security\CodeAuthenticatorEntryPoint:
        autowire: true
    RevisionTen\CMS\Security\BasicAuthenticatorEntryPoint:
        autowire: true
    RevisionTen\CMS\Security\CodeAuthenticator:
        autowire: true
        arguments:
            $config: '%cms%'
            $env: '%kernel.environment%'
    RevisionTen\CMS\Security\BasicAuthenticator:
        autowire: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Security\EntityVoter:
        autoconfigure: true
        autowire: true
        tags: [security.voter]

    # Console commands.
    RevisionTen\CMS\Command\Console\:
        autoconfigure: true
        autowire: true
        tags: [console.command]
        resource: '../../Command/Console'
        exclude: '../../Command/Console/{InstallRolesCommand.php}'
    RevisionTen\CMS\Command\Console\InstallRolesCommand:
        autoconfigure: true
        autowire: true
        tags: [console.command]
        arguments:
            $locale: '%kernel.default_locale%'

    # Services.
    RevisionTen\CMS\Services\IndexService:
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $config: '%cms%'
            $container: '@service_container'
    RevisionTen\CMS\Services\SearchService:
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Services\SecretService:
        autowire: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Services\PageService:
        autowire: true
    RevisionTen\CMS\Services\TaskService:
        autowire: true
    RevisionTen\CMS\Services\MenuService:
        autowire: true
    RevisionTen\CMS\Services\UserService:
        autowire: true
    RevisionTen\CMS\Services\RoleService:
        autowire: true
    RevisionTen\CMS\Services\CacheService:
        autowire: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Services\FileService:
        autowire: true
        arguments:
            $config: '%cms%'
            $project_dir: '%kernel.project_dir%'
    RevisionTen\CMS\Services\AliasSuggester:
        autowire: true
        public: true
        arguments:
            $config: '%cms%'

    # Form types.
    RevisionTen\CMS\Form\Types\UploadType:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Types\ManagedUploadType:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Types\DoctrineType:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Types\CKEditorType:
        autoconfigure: true
        autowire: true
        tags: [form.type]
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Form\PageType:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Elements\Form:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Menu\Page:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Elements\Controller:
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $config: '%cms%'
        tags: [form.type]
    RevisionTen\CMS\Form\Admin\PageStreamReadType:
        autoconfigure: true
        autowire: true
        tags: [ form.type ]

    # Event listeners.
    RevisionTen\CMS\EventListener\WebsiteAndLocaleListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 20 }
    RevisionTen\CMS\EventListener\CurrentWebsiteListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: -10 }

    # Event subscribers.
    RevisionTen\CMS\EventSubscriber\UserSubscriber:
        autowire: true
        autoconfigure: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\EventSubscriber\AggregateSubscriber:
        autowire: true
        autoconfigure: true
    RevisionTen\CMS\EventSubscriber\ExceptionSubscriber:
        autowire: true
        autoconfigure: true
    RevisionTen\CMS\EventSubscriber\PageSubscriber:
        autowire: true
        autoconfigure: true
    RevisionTen\CMS\EventSubscriber\AliasSubscriber:
        autowire: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # Command handlers.
    RevisionTen\CMS\Handler\PageCloneHandler:
        autowire: true
        public: true
    RevisionTen\CMS\Handler\PageRollbackHandler:
        autowire: true
        public: true

