services:
    RevisionTen\CMS\DataCollector\CmsCollector:
        autowire: true
        tags:
            - name:     data_collector
              template: '@cms/Profiler/layout.html.twig'
              id:       'cms.cms_collector'
        public: false
    RevisionTen\CMS\EventListener\WebsiteAndLocaleListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 20 }
    RevisionTen\CMS\EventListener\CurrentWebsiteListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: -10 }
    RevisionTen\CMS\Repository\AliasRepository:
        autowire: true
        autoconfigure: true
        arguments:
            $entityClass: 'RevisionTen\CMS\Model\Alias'
    # TODO: Fix this listener.
    # RevisionTen\CMS\EventListener\LogoutListener:
    #     autowire: true
    #     tags:
    #         - { name: security.logout_listener.main, event: security.logout_listener }
    RevisionTen\CMS\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../../Controller'
        exclude: '../../Controller/{FrontendController.php}'
        tags: ['controller.service_arguments']
    RevisionTen\CMS\Controller\FrontendController:
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Twig\CmsExtension:
        autowire: true
        public: true
        tags: [twig.extension]
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Security\CodeAuthenticator:
        autowire: true
        arguments:
            $config: '%cms%'
            $env: '%kernel.environment%'
    RevisionTen\CMS\Security\BasicAuthenticator:
        autowire: true
        arguments:
            $config: '%cms%'
            $env: '%kernel.environment%'
    RevisionTen\CMS\Security\EntityVoter:
        autoconfigure: true
        autowire: true
        tags: [security.voter]
    RevisionTen\CMS\Command\Console\InstallRolesCommand:
        autoconfigure: true
        autowire: true
        tags: [console.command]
        arguments:
            $locale: '%locale%'
    RevisionTen\CMS\Command\Console\UserCreateCommand:
        autoconfigure: true
        autowire: true
        tags: [console.command]
    RevisionTen\CMS\Command\Console\UserSecretCommand:
        autoconfigure: true
        autowire: true
        tags: [console.command]
    RevisionTen\CMS\Command\Console\UserChangePasswordCommand:
        autoconfigure: true
        autowire: true
        tags: [console.command]
    RevisionTen\CMS\Command\Console\UserMigrateCommand:
        autoconfigure: true
        autowire: true
        tags: [console.command]
    RevisionTen\CMS\Command\Console\MenuMigrateCommand:
        autoconfigure: true
        autowire: true
        tags: [console.command]
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Command\Console\FileMigrateCommand:
        autoconfigure: true
        autowire: true
        tags: [console.command]
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Command\Console\IndexCommand:
        autoconfigure: true
        autowire: true
        public: false
        tags: [console.command]
    RevisionTen\CMS\Command\Console\TasksCommand:
        autoconfigure: true
        autowire: true
        public: false
        tags: [console.command]
    RevisionTen\CMS\Services\IndexService:
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Services\SearchService:
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Services\SecretService:
        autowire: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Services\PageService:
        autowire: true
    RevisionTen\CMS\Services\TaskService:
        autowire: true
    RevisionTen\CMS\Services\MenuService:
        autowire: true
    RevisionTen\CMS\Services\UserService:
        autowire: true
    RevisionTen\CMS\Services\RoleService:
        autowire: true
    RevisionTen\CMS\Services\CacheService:
        autowire: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Services\FileService:
        autowire: true
        arguments:
            $project_dir: '%kernel.project_dir%'
    RevisionTen\CMS\Form\Types\UploadType:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Types\ManagedUploadType:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Types\DoctrineType:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Types\CKEditorType:
        autoconfigure: true
        autowire: true
        tags: [form.type]
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Form\Elements\Form:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Menu\Page:
        autoconfigure: true
        autowire: true
        tags: [form.type]
    RevisionTen\CMS\Form\Elements\Controller:
        autoconfigure: true
        autowire: true
        public: true
        arguments:
            $config: '%cms%'
        tags: [form.type]
    RevisionTen\CMS\EventSubscriber\:
        resource: '../../EventSubscriber/*'
        exclude: '../../EventSubscriber/{AliasSubscriber.php}'
        autowire: true
        autoconfigure: true
    RevisionTen\CMS\EventSubscriber\AliasSubscriber:
        autowire: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    # Listeners must be public!
    RevisionTen\CMS\Listener\:
        public: true
        resource: '../../Listener/*'
        exclude: '../../Listener/{PageBaseListener.php,UserCreateListener.php,UserGenerateSecretListener.php,UserResetPasswordListener.php}'
        autowire: true
    RevisionTen\CMS\Listener\UserCreateListener:
        public: true
        autowire: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Listener\UserGenerateSecretListener:
        public: true
        autowire: true
        arguments:
            $config: '%cms%'
    RevisionTen\CMS\Listener\UserResetPasswordListener:
        public: true
        autowire: true
        arguments:
            $config: '%cms%'
